const types = {
  EXAMPLE_COUNTER_INCREMENT: "EXAMPLE_COUNTER_INCREMENT",
  EXAMPLE_COUNTER_DECREMENT: "EXAMPLE_COUNTER_DECREMENT",
  EXAMPLE_COUNTER_RESET: "EXAMPLE_COUNTER_RESET",
  EXAMPLE_COUNTER_UPDATE_MARGIN: "EXAMPLE_COUNTER_UPDATE_MARGIN",
};

export default types;
