const types = {
  EXAMPLE_API_CALL_START: "EXAMPLE_API_CALL_START",
  EXAMPLE_API_CALL_SUCCESS: "EXAMPLE_API_CALL_SUCCESS",
  EXAMPLE_API_CALL_FAILURE: "EXAMPLE_API_CALL_FAILURE",
};

export default types;
